version: "3.7"
services:
  app:
    image: ghcr.io/silenc3502/fastapi-for-aws-deploy-test:latest
    container_name: docker-fastapi-deploy-server
    ports:
      - 80:80
    networks:
      - app

networks:
  app:
    driver: bridge
